language: java

sudo: false

jdk:
  - oraclejdk8

before_install:
  - mvn install:install-file -Dfile=lib/aws-java-sdk-flow-build-tools-1.10.71.jar -DpomFile=lib/aws-java-sdk-flow-build-tools-1.10.71.pom

script:
  - mvn test
